[package]
name = "dontnote-warp"
version = "0.1.0"
edition = "2021"

[workspace]
members = [".", "config", "api", "migration", "entity"]

[dependencies]
dotenv = "0.15.0"
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
api = { path = "api" }
