//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::note::Entity as Note;
pub use super::user::Entity as User;
pub use super::user_workspace::Entity as UserWorkspace;
pub use super::workspace::Entity as Workspace;
